# Setup
title           : Grid
description     : "Just another simple sass grid system"
keywords        : "simple grid system sass"
url             : http://lefoy.net/grid

author          : lefoy
name            : "lefoy"
website         : http://lefoy.net/

version         : 1.0.0
markdown        : redcarpet
highlighter     : pygments

github          : https://github.com/lefoy
repo            : https://github.com/lefoy/grid

# Assets
sass:
  sass_dir: _scss
  style: :compressed
